- name: 检测redis安装包是否存在
  stat: path={{ soft_path }}/{{ redis_file }}
  register: redis_file_result

- name: 下载安装包
  get_url: url={{ redis_file_url }} dest={{ soft_path }}
  when: not redis_file_result.stat.exists

- name: 分发安装包
  #copy: src={{ soft_path }}/{{ redis_file }} dest={{ soft_path }}/{{ redis_file }}
  copy: src={{ soft_path }}/{{ redis_file }} dest=/root/{{ redis_file }}
  when: not redis_file_result.stat.exists

- name: 安装依赖包
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - tcl
    - gcc-c++
    - libtool
    - make
    
- name: 解压安装包
  #unarchive: src=/data/soft/{{ redis_file }} dest={{ install_path }}
  unarchive: src=/root/{{ redis_file }} dest={{ install_path }}
  when: redis_file_result.stat.exists

- name: 创建目录
  file: path={{ install_path }}/redis-{{ redis_version }}/data state=directory

- name: "编译安装"
  shell: "cd {{ redis_path }} &&  make && make install"
          
- name: "分发启动脚本"
  template:
    src: redis
    dest: /etc/init.d/redis
    mode: 0755

- name: "分发配置文件"
  template:
    src: redis.conf
    dest: "{{ redis_path }}/redis.conf"
    backup: yes

- name: 启动redis
  shell: "/etc/init.d/redis start"
  ignore_errors: true
