#!/bin/bash
MANAGER_CMD=/data/jtb/infra/kafka-manager-1.3.3.23/bin/kafka-manager
MANAGER_LOG=/data/jtb/logs/kafka-manager/kafka-manager.log
Pid_file=/data/jtb/infra/kafka-manager-1.3.3.23/RUNNING_PID
#Pid=`ps -ef |grep -v grep |grep "kafka-manager-1.3.3.23"|awk '{print $2}'`
Pid=`cat ${Pid_file}`
Port=9107
[ -e ${MANAGER_CMD} ] || exit 4
[ -f ${MANAGER_LOG} ] || exit 5

check_status () {
  ps -ef |grep -v grep |grep -w "kafka-manager-1.3.3.23"  &> /dev/null
}

status () {
  check_status
  RETVAL=$?
  if [ $RETVAL -eq 0 ];then
     echo -e "\033[1;35mKafka-manager is Running...\033[0m"
  else
     echo -e "\033[1;35mKafka-manager is Stoped\033[0m"
  fi
}

start () {
  check_status
  RETVAL=$?
  if [ $RETVAL -eq 0 ];then
     echo -e "\033[1;35mKafka-manager is Running...\033[0m"
     exit 1
  else 
     netstat -anp|grep $Port &> /dev/null
     if [ $? -eq 0 ];then
        echo "$Port is already using,Please change another one port.."
        echo -e "Kafka-manager is Start \033[1;31mFaild\033[0m"
        exit 2
     else 
        [ -f ${Pid_file} ] && rm -f ${Pid_file}
        nohup ${MANAGER_CMD} -Dhttp.port=$Port > ${MANAGER_LOG} 2>&1 &
        sleep 2
        check_status
        if [ $? -eq 0 ];then
           echo -e "Kafka-manager is Start \033[1;32mSuccessful\033[0m"
        else 
           echo -e "Kafka-manager is Start \033[1;31mFaild\033[0m"
        fi
     fi
  fi
}

stop () {
  check_status
  RETVAL=$?
  if [ $RETVAL -eq 0 ];then
     kill -9 `echo $Pid`
     sleep 2
     check_status
     if [ $? -eq 0 ];then 
        echo -e "Kafka-manager is Stoped \033[1;31mFaild\033[0m"
     else
        echo -e "Kafka-manager is Stoped \033[1;32mSuccessful\033[0m"
     fi
  else
     echo -e "\033[1;35mKafka-manager is Not Running...\033[0m"
  fi
}

parameter=$1
case $parameter in
"start")
  start
  ;;
"stop")
  stop
  ;;
"restart")
  stop
  start;;
"status")
  status
  ;;
*)
  echo "Usage: One parameter in {start|stop|restart|status}"
esac
