soft_path: "/data/soft"
es_install_path: "/data/jtb/infra"
es_config_path: "/etc/elasticsearch/elasticsearch.yml"
es_log_path: "/data/jtb/logs/es"

es_version: "6.7.0"

es_file: "{{ soft_path }}/elasticsearch-{{ es_version }}.rpm"

es_user: elasticsearch
es_group: elasticsearch

es_http_host: "{{ inventory_hostname }}"
es_http_port: 9200

es_home_dir: "{{ es_install_path }}/es"
es_data_dir: "{{ es_home_dir }}/data"
es_log_dir:  "{{ es_home_dir }}/log"

es_cluster_name: "my-application"
es_node_name: ""
es_node1: "{{ groups['es-nodes'][0] }}"
es_node2: "{{ groups['es-nodes'][1] }}"
es_node3: "{{ groups['es-nodes'][2] }}"
es_unicast_hosts: "[ '{{ es_node1 }}', '{{ es_node2 }}', '{{ es_node3 }}' ]"
