- hosts: new-add
  roles:
  - prepare
  - { role: docker, when: "CONTAINER_RUNTIME == 'docker'" }
  - kube-node
  - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
  - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
  
  tasks:
    - name: 安装安装基础包
      yum:
        name:
          - wget
          - gcc
          - vim
          - ntpdate
          - telnet
          - sysstat
          - git
          - tcpdump
          - net-tools
          - lrzsz
        state: installed
   
    - name: 时间同步
      shell: ntpdate ntp1.aliyun.com
      ignore_errors: true
 
    - name: 时间同步加入计划任务
      cron: "minute=*/30 hour=* day=* month=* weekday=* name='schdule correct from aliyun' job='ntpdate ntp1.aliyun.com > /dev/null 2>&1'"

    - name: 创建文件夹/opt/kube/images
      file: dest=/opt/kube/images state=directory
   
    - name: 分发cluster-addon的离线镜像
      copy: src={{ item }} dest=/opt/kube/images/
      with_fileglob:
        - "{{ base_dir }}/down/coredns*.tar"
        - "{{ base_dir }}/down/dashboard*.tar"
        - "{{ base_dir }}/down/metrics-scraper*.tar"
        - "{{ base_dir }}/down/metrics*.tar"
        - "{{ base_dir }}/down/traefik*.tar"
    
    - name: 导入离线镜像
      shell: ls /opt/kube/images/*.tar |while read n;do {{ bin_dir }}/docker load -i $n ;done
      ignore_errors: true
      when: "CONTAINER_RUNTIME == 'docker'"
