mysql_soft_path: "/data/soft"
mysql_install_path: "/data/jtb/infra"
mysql_slow_log: "/data/jtb/infra/mysql-logs"

mysql_path: "{{ mysql_install_path }}/mysql"
mysql_version: "5.6.34"
mysql_port: "3306"
mysql_file: "{{ mysql_soft_path }}/MySQL-{{ mysql_version }}-1.el7.x86_64.rpm-bundle.tar"
mysql_sock: "{{ mysql_install_path }}/mysql/mysql.sock"

mysql_share_path: "/usr/share/mysql"
mysql_pass: ""
pod_subnet: "172.20.%.%"

mysql_replication_user: "repluser"
mysql_replication_password: "repluser"

##whether remove mysql before install  and whether add mysql replciation user
remove_mysql: "yes"
add_repluser: "yes"
