- name: 创建目录
  file: name={{ item }} state=directory
  with_items:
    - "{{ DIR }}/bin"
    - "{{ DIR }}/logs"
    - "{{ DIR }}/infra"
    - "/etc/yum.repos.d/repo"

- name: 检测jdk是否存在
  stat: path={{ soft_path }}/jdk-8u201-linux-x64.tar.gz
  register: jdk_status

- name: 分发jdk
  copy: src={{ soft_path }}jdk-8u201-linux-x64.tar.gz  dest={{ soft_path }}jdk-8u201-linux-x64.tar.gz
  when: not jdk_status.stat.exists

- name: 解压java环境包
  unarchive:
    src: "{{ JDK_TAR }}"
    dest: "{{ LOCAL_PACK_ROOT }}"

- name: 备份原有的yum仓库
  shell: cd /etc/yum.repos.d/  && mv *.repo  repo

- name: 配置阿里云镜像源
  get_url:
    url: http://mirrors.aliyun.com/repo/Centos-7.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
  when: "inventory_hostname in groups['kube-master'][0]"

- name: 分发阿里云yum仓库
  copy: src=/etc/yum.repos.d/CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo mode=0644

- name: 安装基础常用包
  yum: name={{ item }} state=present
  with_items:
    - wget 
    - gcc 
    - vim 
    - ntpdate 
    - telnet 
    - sysstat 
    - git 
    - tcpdump 
    - net-tools 
    - lrzsz
  tags: install_basic_rpm

#- name: 配置java、jdk环境变量
#  shell: echo "#add java path" >> "{{ PROFILE }}" && \
#         echo  'export JAVA_HOME="{{ LOCAL_PACK_ROOT }}/jdk1.8.0_201"' >> "{{ PROFILE }}"   && \
#         echo 'export JRE_HOME=${JAVA_HOME}/jre' >> "{{ PROFILE }}"  && \ 
#         echo 'export CLASSPATH=.:${JAVA_HOME}/lib/dt.jar:${JAVA_HOME}/lib/tools.jar:${JAVA_HOME}/lib' >> "{{ PROFILE }}"  && \
#         echo 'export PATH=${JAVA_HOME}/bin:${JRE_HOME}/bin:$PATH' >> "{{ PROFILE }}"   && \
#         echo "{{ inventory_hostname }}  logstash.zhkj.com" >> /etc/hosts && \
#         echo "{{ groups['kube-master'][0] }} config.zhkj.com" >> /etc/hosts
#  tags: config_java

- name: 配置java、jdk环境变量
  lineinfile: 'path={{ PROFILE }} line={{ item }}'
  with_items:
    - "#add java path"
    - "export JAVA_HOME={{ LOCAL_PACK_ROOT }}/jdk1.8.0_201"
    - "export JRE_HOME=${JAVA_HOME}/jre"
    - "export CLASSPATH=.:${JAVA_HOME}/lib/dt.jar:${JAVA_HOME}/lib/tools.jar:${JAVA_HOME}/lib"
    - "export PATH=${JAVA_HOME}/bin:${JRE_HOME}/bin:$PATH"

- name: 配置域名解析
  lineinfile: 'path=/etc/hosts line="{{ inventory_hostname }}  logstash.zhkj.com"'
  when: "inventory_hostname in groups['es-nodes']"

- name: 加载环境变量 
  shell: source "{{ PROFILE }}"
  tags: config_java

- name: 设置java软链接
  file:
    src: '{{ LOCAL_PACK_ROOT }}/jdk1.8.0_201/bin/java'
    dest: /usr/bin/java 
    state: link
  tags: config_java

- name: 设置mvn软链接
  file:
    src: '{{ LOCAL_PACK_ROOT }}/apache-maven-3.6.1/bin/mvn'
    dest: /usr/bin/mvn
    state: link
  when: inventory_hostname in group['kube-master'] and ADD_MVN == 'yes'

- name: 修改内核参数配置
  copy: src=sysctl.conf dest=sysctl.conf backup=yes
