---
- hosts: all
  remote_user: root
  vars:
    user: admin
    group: admin
  tasks:
    - name: 创建用户组
      group: name={{ group }} state=present 
      ignore_errors: true
  
    - name: 创建用户{{ user }}
      user: name={{ user }} group={{ group }} shell=/bin/bash
      ignore_errors: true

    - name: 设置{{ user }}用户密码
      user: name={{ item.name }} password={{ item.pass | password_hash('sha512') }} update_password=always
      with_items:
        - { name: admin, pass: 'admim'}

- hosts: kube-node
  remote_user: root
  tasks: 
    - name: 分发各节点需要安装的基础包
      copy: src=/root/{{item}} dest=/root/${{ item }}
      with_items:
        - jdk-8u201-linux-x64.tar.gz
        - nginx-1.14.2.tar.gz
        - kafka_2.12-2.2.0.tgz
        - MySQL-5.6.34-1.el7.x86_64.rpm-bundle.tar
        - elasticsearch-6.7.0.rpm
        - logstash-6.7.0.rpm
        - memsql-client-1.0.0-7e30b698e9.x86_64.rpm
        - memsql-server-6.8.6-5cec6e303c.x86_64.rpm
        - memsql-studio-1.7.1-9754b6b8cc.x86_64.rpm
        - memsql-toolbox-1.2.2-bcf06f20a7.x86_64.rpm

    - name: 分发memsql-server安装包
      copy: 
        src=/root/memsql-server-6.8.6-5cec6e303c.x86_64.rpm
        dest=/home/admin/memsql-server-6.8.6-5cec6e303c.x86_64.rpm

- hosts: master
  remote_user: root
  tasks: 
    - name: 分发安装包到master节点
      copy: src=/root/{{ item }}
            dest=/root
      with_items:
        - Mycat-server-1.6.7.3-release-20190927161129-linux.tar.gz
        - tablesql
        - server.xml
        - rule.xml
        - schema.xml

- hosts: slave
  remote_user: root
  tasks: 
    - name: 分发安装包到slave节点
      copy: src=/root/{{ item }}
            dest=/root
      with_items:
        - redis-5.0.5.tar.gz
        - fastdfs-5.11.tar.gz
        - fastdfs-nginx-module-1.20.tar.gz
        - libfastcommon-1.0.39.tar.gz
        - ocean.jpg
