logstash_install_path: "/data/jtb/infra"
soft_path: "/data/soft"

logstash_version: "6.7.0"
logstash_user: "logstash"
logstash_group: "logstash"

logstash_file: "{{ soft_path }}/logstash-{{ logstash_version }}.rpm"
logstash_config_file: "/etc/logstash/logstash.yml"
logstash_path: "{{ logstash_install_path }}/logstash"

http_port: "9600"
input_port: "9250"
output_port: "4567"

logstash_heap_ms: "3g"
logstash_heap_mx: "3g"
