---
- hosts: kube-node
  remote_user: root
  tasks: 
    - name: copy some rpm to  mysql group
      copy: src=/root/{{item}}
            dest=/root
      with_items:
        - apache-maven-3.6.1-bin.tar.gz
        - jdk-8u201-linux-x64.tar.gz
        - nginx-1.14.2.tar.gz
        - kafka_2.12-2.2.0.tgz
        - MySQL-5.6.34-1.el7.x86_64.rpm-bundle.tar
        - elasticsearch-6.7.0.rpm
        - logstash-6.7.0.rpm
        - memsql-client-1.0.0-7e30b698e9.x86_64.rpm
        - memsql-server-6.8.6-5cec6e303c.x86_64.rpm
        - memsql-studio-1.7.1-9754b6b8cc.x86_64.rpm
        - memsql-toolbox-1.2.2-bcf06f20a7.x86_64.rpm

- hosts: data-001
  remote_user: root
  tasks: 
    - name: copy some rpm to data-001
      copy: src=/root/{{item}}
            dest=/root
      with_items:
        - Mycat-server-1.6-RELEASE-20161028204710-linux.tar.gz
        - tablesql
        - server.xml
        - router.xml
        - rule.xml
        - schema.xml

- hosts: data-002
  remote_user: root
  tasks: 
    - name: copy some rpm to data-002
      copy: src=/root/{{item}}
            dest=/root
      with_items:
        - redis-5.0.5.tar.gz
        - fastdfs-5.11.tar.gz
        - fastdfs-nginx-module-1.20.tar.gz
        - libfastcommon-1.0.39.tar.gz
        - ocean.jpg
